// Ingreso Urgente — entry point generated by the scaffolder (tools/scaffolder).
// A standard game needs no more C++ than this; the rest lives in YAML and
// Lua. Run from the repo root:
//
//   pac_ingreso_urgente                              # default manifest
//   pac_ingreso_urgente path/to/other/game.yaml      # alternate manifest
//   pac_ingreso_urgente --frames 5 --shot out.png    # headless smoke
//   pac_ingreso_urgente --pak resources.pak          # packed build

#include "notebook/notebook_module.hpp"

#include "engine/core/application.hpp"
#include "engine/core/scene_factory.hpp"
#include "engine/pnc/builtin_scenes.hpp"

#include <cstdlib>
#include <string>

namespace {

constexpr char kDefaultManifest[] = "games/ingreso_urgente/data/game.yaml";

} // namespace

int main(int argc, char** argv) {
    std::string manifest = kDefaultManifest;
    pac::core::RunOptions opts;
    if (argc > 0 && argv[0]) {
        opts.argv0 = argv[0]; // hint for the pak-next-to-exe lookup (#109)
    }

    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--frames" && i + 1 < argc) {
            opts.max_frames = std::atoi(argv[++i]);
        } else if (arg.rfind("--frames=", 0) == 0) {
            opts.max_frames = std::atoi(arg.c_str() + 9);
        } else if (arg == "--shot" && i + 1 < argc) {
            opts.screenshot_path = argv[++i];
        } else if (arg.rfind("--shot=", 0) == 0) {
            opts.screenshot_path = arg.c_str() + 7;
        } else if (arg == "--pak" && i + 1 < argc) {
            opts.pak_path = argv[++i];
        } else if (arg.rfind("--pak=", 0) == 0) {
            opts.pak_path = arg.c_str() + 6;
        } else if (!arg.empty() && arg[0] != '-') {
            manifest = arg;
        }
    }

    pac::core::SceneFactory factory;
    pac::pnc::register_builtin_scenes(factory);

    ingreso::notebook::NotebookModule notebook("notebook");
    notebook.registerScenes(factory);
    pac::core::ApplicationHooks hooks;
    hooks.configure = [&notebook](pac::core::EngineContext& ctx, const pac::core::Manifest& manifest) {
        notebook.configure(ctx, manifest);
    };
    return pac::core::run(manifest, factory, opts, hooks);
}
