// {{title}} — entry point, generated by the engine's scaffolder.
//
// This is the whole of it. A standard game needs no more C++: the engine parses
// the command line, loads the manifest, and runs. Everything your game *is* lives
// in data/ — YAML for what exists, Lua for what happens.
//
//   ./build/{{short_name}}                            # the default manifest, below
//   ./build/{{short_name}} path/to/other/game.yaml    # an alternate manifest
//   ./build/{{short_name}} --frames 5 --shot out.png  # headless smoke + screenshot
//   ./build/{{short_name}} --pak resources.pak        # a packed build
//
// Reach for C++ only when you need a scene type the engine doesn't have — see the
// engine's examples/06_cpp_scene.
#include "engine/pnc/game_app.hpp"

int main(int argc, char** argv) {
    return pac::pnc::run_game_main(argc, argv, "data/game.yaml");
}
