-- Behaviour for room {{room_id}}, generated by `tools.scaffolder add room`.
-- Static geometry and hotspot declarations live in {{room_id}}.yaml.

return {
    on_load = function()
    end,

    on_unload = function()
    end,

    hotspots = {
        -- sign = {
        --     look_at = function()
        --         return "Un cartel sin texto."
        --     end,
        -- },
    },
}
