// {{title}} — entry point, generated by the engine's scaffolder.
//
// The launcher is platform-specific only in how resources are supplied. The
// `pac::game` target implements the same composition factory for every platform.
//
//   ./build/{{short_name}}                            # the default manifest, below
//   ./build/{{short_name}} path/to/other/game.yaml    # an alternate manifest
//   ./build/{{short_name}} --frames 5 --shot out.png  # headless smoke + screenshot
//   ./build/{{short_name}} --pak resources.pak        # a packed build
//
// Reach for C++ only when you need a scene type the engine doesn't have — see the
// engine's examples/06_cpp_scene.
#include "engine/core/game.hpp"

int main(int argc, char** argv) {
    pac::core::RunOptions options;
    const std::string manifest =
        pac::core::parse_run_options(argc, argv, options, "data/game.yaml");
    std::unique_ptr<pac::core::Game> game = pac::game::create();
    return pac::core::run_game(manifest, *game, options);
}
